// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/nif.proto

package nif_tools

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NifApiClient is the client API for NifApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NifApiClient interface {
	GetControlDigit(ctx context.Context, in *ControlDigitRequest, opts ...grpc.CallOption) (*ControlDigitResponse, error)
}

type nifApiClient struct {
	cc grpc.ClientConnInterface
}

func NewNifApiClient(cc grpc.ClientConnInterface) NifApiClient {
	return &nifApiClient{cc}
}

func (c *nifApiClient) GetControlDigit(ctx context.Context, in *ControlDigitRequest, opts ...grpc.CallOption) (*ControlDigitResponse, error) {
	out := new(ControlDigitResponse)
	err := c.cc.Invoke(ctx, "/main.NifApi/GetControlDigit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NifApiServer is the server API for NifApi service.
// All implementations must embed UnimplementedNifApiServer
// for forward compatibility
type NifApiServer interface {
	GetControlDigit(context.Context, *ControlDigitRequest) (*ControlDigitResponse, error)
	mustEmbedUnimplementedNifApiServer()
}

// UnimplementedNifApiServer must be embedded to have forward compatible implementations.
type UnimplementedNifApiServer struct {
}

func (UnimplementedNifApiServer) GetControlDigit(context.Context, *ControlDigitRequest) (*ControlDigitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetControlDigit not implemented")
}
func (UnimplementedNifApiServer) mustEmbedUnimplementedNifApiServer() {}

// UnsafeNifApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NifApiServer will
// result in compilation errors.
type UnsafeNifApiServer interface {
	mustEmbedUnimplementedNifApiServer()
}

func RegisterNifApiServer(s grpc.ServiceRegistrar, srv NifApiServer) {
	s.RegisterService(&NifApi_ServiceDesc, srv)
}

func _NifApi_GetControlDigit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlDigitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NifApiServer).GetControlDigit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.NifApi/GetControlDigit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NifApiServer).GetControlDigit(ctx, req.(*ControlDigitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NifApi_ServiceDesc is the grpc.ServiceDesc for NifApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NifApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.NifApi",
	HandlerType: (*NifApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetControlDigit",
			Handler:    _NifApi_GetControlDigit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/nif.proto",
}
